config/routes.rb
Rails.application.routes.draw do
  root "usuarios#index"
  resources :usuarios do
    collection do
      get 'search'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    if params[:query].present?
      @usuarios = Usuario.search(params[:query])
    else
      @usuarios = Usuario.all
    end
  end

  def search
    @usuarios = Usuario.where('nome ILIKE ?', "%#{params[:query]}%")
    respond_to do |format|
      if turbo_frame_request?
        format.html { render partial: 'usuarios/datatable', locals: { usuarios: @usuarios } }
      else
        format.html { render :index }
      end
    end
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome, :endereco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_datatable.html.erb
<%= turbo_frame_tag 'search_usuario' do %>
  <div id="usuarios">
    <% usuarios.each do |usuario| %>
      <%= render usuario %>
      <p>
        <%= link_to "Show this usuario", usuario %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nome:</strong>
    <%= usuario.nome %>
  </p>

  <p>
    <strong>endereco:</strong>
    <%= usuario.endereco %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with url: search_usuarios_path, method: :get, data: {turbo_frame: 'search_usuario', controller: 'search', action: 'keyup->search# search_perform'} do |f| %>
  <%= f.text_field :query, value: params[:query] %>
<% end %>

<h1>Usuarios</h1>

<%= render partial: 'usuarios/datatable', locals: {usuarios: @usuarios} %>

<%= link_to "New usuario", new_usuario_path %>

<div><%= "lorem ipsum" * 50 %></div>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>